#!/usr/bin/env python3
"""Create a per-trial execution plan for SFT trajectory collection.

Output is a JSONL where each line is a fully-specified trial:
  - which bench / task_id / mode / trial_index
  - exact runner argv to invoke
  - exact env vars to set (date prefix, exp version, model)
  - exact output paths the runner WILL write to (so the launcher can
    skip-if-completed and the collector can find trajectories)

The launcher then takes this plan + filters and runs the matching trials.
The collector then takes the same plan + reads the trajectories.

This separation matters because:
  - launcher and collector must agree on file layout → derive both from one place
  - re-launching with different filters (e.g. only teacher mode) shouldn't
    require re-generating the plan
  - everything that decides "where output lives" goes through `make_record`

Mode taxonomy (2026-04-26 design — explicit-branch + reflection):

  student_baseline       — 9B, NO retrieval skills injected. Optional sanity-
                           check arm. Default 0 trials (set student_baseline_trials
                           >0 in config to enable). Not a direct SFT candidate
                           because its prompt has no skill list.

  student_use_skill      — 9B, retrieval skills injected, system prompt
                           AUGMENTED with implicit "Note: skills are validated,
                           reading them helps" (UNIFIED_IMPLICIT_MODE=use_skill).
                           Direct SFT candidate. The implicit text is stripped
                           from the saved trajectory before SFT export so the
                           model doesn't learn to respond to artificial hints.

  student_no_skill       — 9B, retrieval skills STILL injected (so the prompt
                           format is identical to student_use_skill), but the
                           implicit instruction tells the agent to NOT read
                           any skill files and solve from its own knowledge
                           (UNIFIED_IMPLICIT_MODE=no_skill). Direct SFT
                           candidate. Same strip-on-export.

  teacher_retrieval      — configured teacher model, retrieval skills injected,
                           no implicit. Used as fallback for tasks where 9B
                           fails entirely.

  teacher_retrieval_reflection
                         — Default Phase 2 fallback mode. Generated post-hoc by
                           make_teacher_fallback_plan.py for tasks whose ALL
                           Phase 1 student trials failed. Runs the configured
                           teacher with retrieval and a reflection context
                           containing prior 9B trajectories + verifier/launcher
                           feedback.

  student_*_reflection   — Legacy Phase 2 retry mode. Generated by
                           make_reflection_plan.py; kept for ablation but not
                           the default experiment-root path.

The split between "explicit branches in Phase 1" + "reflection in Phase 2" is
deliberate: it gives both classes of solutions (skill-using and skill-free)
explicit sampling budget, so we don't depend on luck to discover both paths
for any given task.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from common import (
    DEFAULT_CONFIG,
    PROJECT_ROOT,
    display_path,
    experiment_plan_path,
    experiment_results_root,
    experiment_root,
    experiment_sft_log_root,
    load_json,
    load_retrieval_task_ids,
    filter_known_bad_tasks,
    model_short,
    output_bench_name,
    repo_path,
    safe_slug,
    trajectory_file_name,
)


# ---------------------------------------------------------------------------
# Task subset selection (for pilots — we don't always want all train tasks)
# ---------------------------------------------------------------------------

def select_tasks(tasks: list[str], limit: int) -> list[str]:
    """Pick `limit` tasks evenly spaced across the input list.

    limit <= 0  → all tasks (no pilot)
    limit == 1  → first task only (deterministic, easy to repro)
    limit >= 2  → endpoints + evenly spaced midpoints

    Note: input list IS NOT re-sorted — we trust the caller's order, which
    typically comes from the split file (already sorted).
    """
    if limit <= 0 or limit >= len(tasks):
        return list(tasks)
    if limit == 1:
        return [tasks[0]]
    # Linear interpolation between [0, len-1] inclusive.
    selected: list[str] = []
    for index in range(limit):
        position = int(round(index * (len(tasks) - 1) / (limit - 1)))
        selected.append(tasks[position])
    return selected


# ---------------------------------------------------------------------------
# Env vars expected by the runners
# ---------------------------------------------------------------------------

def build_env_updates(
    date: str,
    exp_version: str,
    model: str,
    run_id: str = "",
    implicit_mode: str = "",
    reflection_context: str = "",
) -> dict[str, str]:
    """Env vars the unified runners read.

    UNIFIED_RESULTS_DATE  — overrides the auto date prefix in result paths.
                            Must match what we encode into `result_dir` below,
                            otherwise launcher/collector go to wrong dir.
    UNIFIED_EXP_VERSION   — slug for `<EXP>_<arm>` subdir naming.
    UNIFIED_MODEL / PHASE_B_MODEL — model name passed via API; runner ALSO
                            takes --model on argv but env var is a backup.
    UNIFIED_DISABLE_THINKING / PRESENCE_PENALTY / EARLY_STOP_N — sampling
                            params that should match what we used in the
                            evaluation runs (so SFT data matches deploy).
    UNIFIED_IMPLICIT_MODE   — "use_skill" / "no_skill" / "" — selects which
                            implicit-instruction text the runner appends to
                            the system prompt. See implicit_instruction.py.
    UNIFIED_REFLECTION_CONTEXT — for Phase 2 reflection trials only. Free
                            text (typically last assistant turn + finish_reason
                            of the previous failed attempt). Runner wraps it
                            and appends to system prompt; collector strips.
    OPENAI_API_KEY/BASE   — local SGLang endpoint; can be overridden if user
                            already has them in env (we honor existing values).
    """
    env = {
        "DOCKER_HOST": "tcp://127.0.0.1:2375",
        "NO_PROXY": "127.0.0.1,localhost,0.0.0.0",
        "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY", "sk-local-anything"),
        "OPENAI_API_BASE": os.environ.get("OPENAI_API_BASE", "http://127.0.0.1:30000/v1"),
        "HF_ENDPOINT": os.environ.get("HF_ENDPOINT", "https://hf-mirror.com"),
        "UNIFIED_RESULTS_DATE": date,
        "UNIFIED_RUN_ID": run_id,
        "EXPERIMENT_ROOT": display_path(experiment_root(run_id)) if run_id else "",
        "UNIFIED_EXP_VERSION": exp_version,
        "UNIFIED_MODEL": model,
        "PHASE_B_MODEL": model,
        "UNIFIED_DISABLE_THINKING": "1",
        "UNIFIED_PRESENCE_PENALTY": "1.5",
        "UNIFIED_EARLY_STOP_N": "3",
    }
    if implicit_mode:
        env["UNIFIED_IMPLICIT_MODE"] = implicit_mode
    if reflection_context:
        env["UNIFIED_REFLECTION_CONTEXT"] = reflection_context
    if not run_id:
        env.pop("UNIFIED_RUN_ID", None)
        env.pop("EXPERIMENT_ROOT", None)
    return env


# ---------------------------------------------------------------------------
# Per-bench runner invocation
# ---------------------------------------------------------------------------

def runner_argv(
    bench: str,
    task_id: str,
    model: str,
    api_base: str | None,
    arm: str,
    retrieval_jsonl: str | None,
    retrieval_top_n: int,
    max_turns: int,
    max_time: int | None = None,
) -> list[str]:
    """Build the python argv to run one task in one bench.

    Three runner scripts handle five benches:
      - run_unified_harbor.py  → tb2 / sb_ns / seta_synth (all harbor-style)
      - run_unified_swe.py     → swe_lite (own runtime, swe-gym images)
      - run_unified_claw.py    → claw (shared mock infra, internal parallel)

    `arm`:
      "baseline"        → no skill injection
      "retrieval"       → --inject-retrieval-skills <jsonl>
      "top1_skill_text" → --inject-top1-skill-text <jsonl>
    """
    if bench in {"tb2", "sb_ns", "seta_synth"}:
        argv = [
            "python3", "-u",
            "GeneralAgent/eval_scripts/unified_runner/run_unified_harbor.py",
            "--model", model,
            "--api-base", api_base or "http://127.0.0.1:30000/v1",
            "--max-turns", str(max_turns),
            "--retrieval-top-n", str(retrieval_top_n),
        ]
        if max_time is not None:
            argv += ["--max-time", str(max_time)]
        if bench == "tb2":
            argv += ["--dataset", "tb2", "--task", task_id]
        elif bench == "sb_ns":
            argv += ["--dataset", "skillsbench", "--variant", "no-skills", "--task", task_id]
        else:  # seta_synth
            argv += ["--dataset", "seta-synth", "--task", task_id]

    elif bench == "swe_lite":
        argv = [
            "python3", "-u",
            "GeneralAgent/eval_scripts/unified_runner/run_unified_swe.py",
            "--model", model,
            "--api-base", api_base or "http://127.0.0.1:30000/v1",
            "--max-turns", str(max_turns),
            "--retrieval-top-n", str(retrieval_top_n),
            "--instance-file", "GeneralAgent/eval_scripts/prebake_images/swe_lite_100.txt",
            "--instance", task_id,
        ]
        if max_time is not None:
            argv += ["--max-time", str(max_time)]

    elif bench == "claw":
        # Claw runner has its OWN parallel scheduler (--parallel N) for
        # multi-task; we always pass parallel=1 and let the launcher
        # serialize trial-level concurrency via claw_lock. --max-turns is
        # NOT a claw arg (it's hardcoded per-task in claw config), so we
        # don't pass it.
        argv = [
            "python3", "-u",
            "GeneralAgent/eval_scripts/unified_runner/run_unified_claw.py",
            "--model", model,
            "--api-base", api_base or "http://127.0.0.1:30000/v1",
            "--retrieval-top-n", str(retrieval_top_n),
            "--tasks", task_id,
            "--parallel", "1",
        ]

    else:
        raise ValueError(f"unknown bench: {bench}")

    if arm in {"retrieval", "top1_skill_text"}:
        if not retrieval_jsonl:
            raise ValueError(f"{arm} arm needs retrieval_jsonl for {bench}")
        if arm == "retrieval":
            argv += ["--inject-retrieval-skills", retrieval_jsonl]
        else:
            argv += ["--inject-top1-skill-text", retrieval_jsonl]
    return argv


# ---------------------------------------------------------------------------
# One trial record = one row of the plan JSONL
# ---------------------------------------------------------------------------

def make_record(
    *,
    run_id: str,
    date: str,
    bench: str,
    task_id: str,
    split: str,
    mode: str,
    model_role: str,
    model: str,
    arm: str,
    trial_index: int,
    retrieval_jsonl: str | None,
    retrieval_top_n: int,
    max_turns: int,
    retrieval_covered: bool,
    max_time: int | None = None,
    implicit_mode: str = "",
    reflection_context: str = "",
) -> dict[str, Any]:
    """Materialize all paths and argv up-front so launcher/collector agree.

    The crucial invariant: `result_dir` MUST be where the runner actually
    writes (it derives from UNIFIED_RESULTS_DATE + UNIFIED_EXP_VERSION + arm
    via results_subdir() in unified_runner/base.py). If you change the env
    vars here without changing `result_dir`, the collector won't find the
    trajectory.
    """
    model_tag = model_short(model)
    task_slug = safe_slug(task_id, max_len=42)
    # exp_version embeds run_id so different SFT runs land in different
    # output dirs; the trial_index suffix lets parallel trials of the same
    # task coexist. Put date/run_id first so result dirs sort chronologically.
    run_tag = run_id if str(run_id).startswith(date) else f"{date}_{run_id}"
    exp_version = safe_slug(
        f"{run_tag}_sft_{model_tag}_{mode}_{bench}_{task_slug}_t{trial_index:02d}",
        max_len=120,
    )
    experiment = f"{exp_version}_{arm}"
    result_dir = experiment_results_root(run_id) / output_bench_name(bench) / experiment
    trajectory_path = result_dir / "trajectories" / trajectory_file_name(bench, task_id)
    incremental_path = result_dir / "incremental.jsonl"
    log_path = (
        experiment_sft_log_root(run_id)
        / bench
        / mode
        / f"{safe_slug(task_id, 80)}__t{trial_index:02d}.log"
    )
    env_updates = build_env_updates(
        date, exp_version, model,
        run_id=run_id,
        implicit_mode=implicit_mode,
        reflection_context=reflection_context,
    )
    argv = runner_argv(
        bench=bench,
        task_id=task_id,
        model=model,
        api_base=env_updates.get("OPENAI_API_BASE"),
        arm=arm,
        retrieval_jsonl=retrieval_jsonl,
        retrieval_top_n=retrieval_top_n,
        max_turns=max_turns,
        max_time=max_time,
    )
    # direct_sft_candidate: collector exports messages from this trial into
    # sft_messages.jsonl iff the trial succeeds. student_baseline is excluded
    # because its prompt has no skill list (different distribution from
    # deployment). All retrieval-arm modes are candidates including reflection
    # variants — collector strips the implicit/reflection text before export.
    DIRECT_SFT_MODES = {
        "student_use_skill", "student_no_skill",
        "student_use_skill_reflection", "student_no_skill_reflection",
        "teacher_retrieval", "teacher_retrieval_reflection",
    }
    return {
        "schema_version": 1,
        "trial_id": f"{run_id}::{bench}::{task_id}::{mode}::t{trial_index:02d}",
        "run_id": run_id,
        "date": date,
        "bench": bench,
        "task_id": task_id,
        "split": split,
        "mode": mode,
        "model_role": model_role,
        "model": model,
        "arm": arm,
        "trial_index": trial_index,
        "retrieval_jsonl": retrieval_jsonl,
        "retrieval_top_n": retrieval_top_n,
        "retrieval_covered": retrieval_covered,
        "expected_skill_available": arm in {"retrieval", "top1_skill_text"},
        "implicit_mode": implicit_mode,
        # reflection_context only carried in env (long string); plan record
        # just notes whether one was attached (boolean) so launcher and
        # collector can check without parsing env.
        "has_reflection_context": bool(reflection_context),
        "direct_sft_candidate": mode in DIRECT_SFT_MODES,
        # classification_candidate: trial used to bucket the task as
        # no_skill_solvable / skill_helpful / etc. Only student trials
        # contribute (teacher solvability is not the question we care about).
        "classification_candidate": model_role == "student",
        "env": env_updates,
        "argv": argv,
        "command_preview": shlex.join(argv),
        "result_dir": display_path(result_dir),
        "incremental_path": display_path(incremental_path),
        "trajectory_path": display_path(trajectory_path),
        "log_path": display_path(log_path),
    }


# ---------------------------------------------------------------------------
# Plan assembly
# ---------------------------------------------------------------------------

def build_plan(
    config: dict[str, Any],
    splits: dict[str, Any],
    run_id: str,
    date: str,
    benches: list[str],
    split_name: str,
    pilot_per_bench: int,
    include_teacher: bool,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Expand config + splits into Phase 1 trial records.

    Per task, generates:
      - K_use trials of student_use_skill (UNIFIED_IMPLICIT_MODE=use_skill)
      - K_no trials of student_no_skill   (UNIFIED_IMPLICIT_MODE=no_skill)
      - K_base trials of student_baseline (only if budget > 0; default 0)
      - K_teach trials of teacher_retrieval (only if include_teacher)

    Phase 2 trials are NOT generated here — they require Phase 1 results to
    know which tasks failed and what verifier feedback they produced. Default
    Pipeline Phase 2 uses make_teacher_fallback_plan.py.
    """
    budgets = config["budgets"]
    student_model = config["models"]["student"]
    teacher_model = config["models"]["teacher"]
    retrieval_files = config["frozen_retrieval"]["files"]
    retrieval_top_n = int(budgets["retrieval_top_n"])
    per_bench_budgets = budgets.get("per_bench_budgets", {})
    warnings: list[str] = []
    records: list[dict[str, Any]] = []

    # Pre-load coverage sets so we can warn about tasks the retrieval pipeline
    # doesn't have entries for (will run as effective baseline if forced).
    retrieval_task_ids = {
        bench: load_retrieval_task_ids(path_value)
        for bench, path_value in retrieval_files.items()
    }

    for bench in benches:
        if bench not in splits["benches"]:
            raise ValueError(
                f"bench {bench!r} not in split file {sorted(splits['benches'])}"
            )
        tasks = filter_known_bad_tasks(bench, list(splits["benches"][bench][split_name]))
        tasks = select_tasks(tasks, pilot_per_bench)
        retrieval_jsonl = retrieval_files.get(bench)
        covered_ids = retrieval_task_ids.get(bench, set())
        bench_budgets = {
            **budgets,
            **(per_bench_budgets.get(bench, {}) if isinstance(per_bench_budgets, dict) else {}),
        }
        max_turns = int(bench_budgets["max_turns"])
        max_time = int(bench_budgets["max_time"]) if bench_budgets.get("max_time") is not None else None
        use_skill_trials = int(bench_budgets.get("student_use_skill_trials", 8))
        no_skill_trials = int(bench_budgets.get("student_no_skill_trials", 8))
        baseline_trials = int(bench_budgets.get("student_baseline_trials", 0))
        teacher_trials = int(bench_budgets.get("teacher_trials", 4))

        for task_id in tasks:
            retrieval_covered = task_id in covered_ids
            if not retrieval_covered:
                warnings.append(
                    f"{bench}/{task_id}: missing retrieval entry in {retrieval_jsonl}"
                )

            # Phase 1.A — student_use_skill (with retrieval + use-skill nudge).
            for trial_index in range(use_skill_trials):
                records.append(make_record(
                    run_id=run_id, date=date, bench=bench, task_id=task_id,
                    split=split_name, mode="student_use_skill",
                    model_role="student", model=student_model, arm="retrieval",
                    trial_index=trial_index, retrieval_jsonl=retrieval_jsonl,
                    retrieval_top_n=retrieval_top_n, max_turns=max_turns,
                    max_time=max_time,
                    retrieval_covered=retrieval_covered,
                    implicit_mode="use_skill",
                ))

            # Phase 1.B — student_no_skill (with retrieval + no-skill nudge).
            for trial_index in range(no_skill_trials):
                records.append(make_record(
                    run_id=run_id, date=date, bench=bench, task_id=task_id,
                    split=split_name, mode="student_no_skill",
                    model_role="student", model=student_model, arm="retrieval",
                    trial_index=trial_index, retrieval_jsonl=retrieval_jsonl,
                    retrieval_top_n=retrieval_top_n, max_turns=max_turns,
                    max_time=max_time,
                    retrieval_covered=retrieval_covered,
                    implicit_mode="no_skill",
                ))

            # Optional control — student_baseline (NO retrieval injected,
            # NO implicit). Default disabled because it adds inference cost
            # without contributing SFT data.
            for trial_index in range(baseline_trials):
                records.append(make_record(
                    run_id=run_id, date=date, bench=bench, task_id=task_id,
                    split=split_name, mode="student_baseline",
                    model_role="student", model=student_model, arm="baseline",
                    trial_index=trial_index, retrieval_jsonl=None,
                    retrieval_top_n=retrieval_top_n, max_turns=max_turns,
                    max_time=max_time,
                    retrieval_covered=True,
                ))

            # Optional teacher fallback — same retrieval prompt as students,
            # but no implicit (we want teacher's natural exploration).
            if include_teacher:
                for trial_index in range(teacher_trials):
                    records.append(make_record(
                        run_id=run_id, date=date, bench=bench, task_id=task_id,
                        split=split_name, mode="teacher_retrieval",
                        model_role="teacher", model=teacher_model, arm="retrieval",
                        trial_index=trial_index, retrieval_jsonl=retrieval_jsonl,
                        retrieval_top_n=retrieval_top_n, max_turns=max_turns,
                        max_time=max_time,
                        retrieval_covered=retrieval_covered,
                    ))
    return records, warnings


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file_handle:
        for record in records:
            file_handle.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument(
        "--splits",
        default="GeneralAgent/sft_data_collection/outputs/splits/default/holdout_split.json",
    )
    parser.add_argument("--out", default="", help="Plan output path; default experiments/<date>/<run_id>/plans/<run_id>.jsonl")
    parser.add_argument("--run-id", default="",
                        help="Run identifier (becomes part of every output path); "
                             "default = pilot_<UTC timestamp>")
    parser.add_argument("--date", default=datetime.now(timezone.utc).strftime("%Y%m%d"),
                        help="Date prefix for results dir (UNIFIED_RESULTS_DATE)")
    parser.add_argument("--benches", nargs="+",
                        default=["claw", "tb2", "sb_ns", "seta_synth", "swe_lite"])
    parser.add_argument("--split", choices=["train", "test"], default="train",
                        help="Use train or test side of holdout_split.json")
    parser.add_argument("--pilot-per-bench", type=int, default=0,
                        help="Limit to N evenly-spaced tasks per bench (0 = all)")
    parser.add_argument("--include-teacher", action="store_true",
                        help="Also generate teacher_retrieval records")
    args = parser.parse_args()

    run_id = args.run_id or f"{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_pilot"
    output_path = repo_path(args.out) if args.out else experiment_plan_path(run_id)
    config = load_json(args.config)
    splits = load_json(args.splits)
    records, warnings = build_plan(
        config=config,
        splits=splits,
        run_id=run_id,
        date=args.date,
        benches=args.benches,
        split_name=args.split,
        pilot_per_bench=args.pilot_per_bench,
        include_teacher=args.include_teacher,
    )
    write_jsonl(output_path, records)
    warning_path = output_path.with_suffix(".warnings.txt")
    warning_path.write_text("\n".join(warnings) + ("\n" if warnings else ""), encoding="utf-8")
    try:
        display_output = output_path.relative_to(PROJECT_ROOT)
    except ValueError:
        display_output = output_path
    try:
        display_warnings = warning_path.relative_to(PROJECT_ROOT)
    except ValueError:
        display_warnings = warning_path
    print(f"wrote {len(records)} trial records to {display_output}")
    print(f"warnings: {len(warnings)} ({display_warnings})")


if __name__ == "__main__":
    main()
